# Generated by GitHub Copilot
"""API tests for agent-tracer trace ingestion and retrieval."""

from __future__ import annotations

from fastapi.testclient import TestClient

from api.main import app, tracer

client = TestClient(app)


def test_health_endpoint_returns_ok() -> None:
    """Ensures health endpoint responds with service status."""
    tracer.clear()
    response = client.get("/health")

    assert response.status_code == 200
    payload = response.json()
    assert payload["status"] == "ok"
    assert payload["service"] == "agent-tracer"


def test_trace_ingestion_and_latest_retrieval() -> None:
    """Ensures trace steps can be ingested and fetched."""
    tracer.clear()

    ingest = client.post(
        "/trace",
        json={
            "steps": [
                {
                    "node_name": "retrieve",
                    "input_state": {"query": "hello"},
                    "output_state": {"docs": ["d1"]},
                    "latency_ms": 3.5,
                    "token_usage": 21,
                    "status": "success",
                }
            ]
        },
    )

    assert ingest.status_code == 200
    assert ingest.json()["stored"] == 1

    latest = client.get("/trace/latest")
    assert latest.status_code == 200
    payload = latest.json()
    assert payload["count"] == 1
    assert payload["steps"][0]["node_name"] == "retrieve"


def test_clear_trace_endpoint() -> None:
    """Ensures trace store can be cleared via API."""
    tracer.clear()

    client.post(
        "/trace",
        json={
            "steps": [
                {
                    "node_name": "plan",
                    "input_state": {},
                    "output_state": {},
                    "latency_ms": 1.2,
                    "token_usage": 5,
                    "status": "success",
                }
            ]
        },
    )

    clear = client.delete("/trace")
    assert clear.status_code == 200
    assert clear.json()["status"] == "cleared"

    latest = client.get("/trace/latest")
    assert latest.status_code == 200
    assert latest.json()["count"] == 0
