# Generated by GitHub Copilot
"""Tracing primitives for LangGraph-style node execution."""

from __future__ import annotations

import inspect
import json
import threading
import time
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from typing import Any, Dict, Iterable, List, Mapping, MutableMapping, Optional


@dataclass
class TraceStep:
    """Represents one traced graph node execution."""

    node_name: str
    input_state: Any
    output_state: Any
    latency_ms: float
    token_usage: int
    timestamp: str
    status: str
    error: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Converts this trace step into a JSON-serializable mapping."""
        return asdict(self)


class AgentTracer:
    """Instruments graph nodes and stores timeline-friendly trace steps."""

    def __init__(self) -> None:
        """Initializes an empty tracer state."""
        self._steps: List[TraceStep] = []
        self._lock = threading.Lock()

    def clear(self) -> None:
        """Removes all recorded trace steps."""
        with self._lock:
            self._steps.clear()

    def get_steps(self) -> List[TraceStep]:
        """Returns a snapshot copy of current trace steps."""
        with self._lock:
            return list(self._steps)

    def add_step(self, step: TraceStep) -> None:
        """Appends an externally provided trace step."""
        with self._lock:
            self._steps.append(step)

    def trace(self, graph: Any) -> Any:
        """Instruments graph nodes in place and returns the same graph object."""
        self._instrument_nodes(graph)
        return graph

    def export_json(self, indent: int = 2) -> str:
        """Exports the full trace history as a JSON string."""
        payload = [step.to_dict() for step in self.get_steps()]
        return json.dumps(payload, indent=indent, default=self._json_fallback)

    def _instrument_nodes(self, graph: Any) -> None:
        """Wraps each node callable to capture execution metadata."""
        nodes = self._resolve_nodes_mapping(graph)
        if nodes is None:
            self._instrument_fallback_invocation(graph)
            return

        for node_name, handler in list(nodes.items()):
            if getattr(handler, "__agent_tracer_wrapped__", False):
                continue

            if inspect.iscoroutinefunction(handler):
                wrapped = self._wrap_async_handler(node_name, handler)
            else:
                wrapped = self._wrap_sync_handler(node_name, handler)

            setattr(wrapped, "__agent_tracer_wrapped__", True)
            nodes[node_name] = wrapped

    def _resolve_nodes_mapping(self, graph: Any) -> Optional[MutableMapping[str, Any]]:
        """Resolves a mutable mapping of graph nodes when available."""
        candidates = [getattr(graph, "nodes", None), getattr(graph, "_nodes", None)]
        for candidate in candidates:
            if isinstance(candidate, MutableMapping):
                return candidate

        get_nodes = getattr(graph, "get_nodes", None)
        if callable(get_nodes):
            result = get_nodes()
            if isinstance(result, MutableMapping):
                return result
        return None

    def _instrument_fallback_invocation(self, graph: Any) -> None:
        """Wraps invoke/ainvoke when per-node instrumentation is not exposed."""
        invoke = getattr(graph, "invoke", None)
        if callable(invoke) and not getattr(invoke, "__agent_tracer_wrapped__", False):
            def invoke_wrapper(*args: Any, **kwargs: Any) -> Any:
                """Records a fallback graph-level invocation step."""
                return self._execute_and_record("graph.invoke", invoke, args, kwargs)

            setattr(invoke_wrapper, "__agent_tracer_wrapped__", True)
            setattr(graph, "invoke", invoke_wrapper)

        ainvoke = getattr(graph, "ainvoke", None)
        if callable(ainvoke) and not getattr(ainvoke, "__agent_tracer_wrapped__", False):
            async def ainvoke_wrapper(*args: Any, **kwargs: Any) -> Any:
                """Records a fallback graph-level async invocation step."""
                return await self._execute_and_record_async("graph.ainvoke", ainvoke, args, kwargs)

            setattr(ainvoke_wrapper, "__agent_tracer_wrapped__", True)
            setattr(graph, "ainvoke", ainvoke_wrapper)

    def _wrap_sync_handler(self, node_name: str, handler: Any) -> Any:
        """Creates a sync wrapper that records node execution details."""
        def wrapped(*args: Any, **kwargs: Any) -> Any:
            """Executes a node and records a trace step."""
            return self._execute_and_record(node_name, handler, args, kwargs)

        return wrapped

    def _wrap_async_handler(self, node_name: str, handler: Any) -> Any:
        """Creates an async wrapper that records node execution details."""
        async def wrapped(*args: Any, **kwargs: Any) -> Any:
            """Executes an async node and records a trace step."""
            return await self._execute_and_record_async(node_name, handler, args, kwargs)

        return wrapped

    def _execute_and_record(
        self,
        node_name: str,
        handler: Any,
        args: Iterable[Any],
        kwargs: Mapping[str, Any],
    ) -> Any:
        """Runs a sync handler and persists a trace record."""
        started = time.perf_counter()
        input_state = self._extract_state(args, kwargs)
        status = "success"
        error_text: Optional[str] = None
        output_state: Any = None

        try:
            output_state = handler(*args, **dict(kwargs))
            return output_state
        except Exception as exc:
            status = "error"
            error_text = str(exc)
            raise
        finally:
            elapsed_ms = (time.perf_counter() - started) * 1000.0
            self._record_step(
                node_name=node_name,
                input_state=input_state,
                output_state=output_state,
                latency_ms=elapsed_ms,
                status=status,
                error_text=error_text,
            )

    async def _execute_and_record_async(
        self,
        node_name: str,
        handler: Any,
        args: Iterable[Any],
        kwargs: Mapping[str, Any],
    ) -> Any:
        """Runs an async handler and persists a trace record."""
        started = time.perf_counter()
        input_state = self._extract_state(args, kwargs)
        status = "success"
        error_text: Optional[str] = None
        output_state: Any = None

        try:
            output_state = await handler(*args, **dict(kwargs))
            return output_state
        except Exception as exc:
            status = "error"
            error_text = str(exc)
            raise
        finally:
            elapsed_ms = (time.perf_counter() - started) * 1000.0
            self._record_step(
                node_name=node_name,
                input_state=input_state,
                output_state=output_state,
                latency_ms=elapsed_ms,
                status=status,
                error_text=error_text,
            )

    def _record_step(
        self,
        node_name: str,
        input_state: Any,
        output_state: Any,
        latency_ms: float,
        status: str,
        error_text: Optional[str],
    ) -> None:
        """Constructs and stores a trace step with derived token usage."""
        token_usage = self._estimate_tokens(input_state, output_state)
        step = TraceStep(
            node_name=node_name,
            input_state=self._clone_for_trace(input_state),
            output_state=self._clone_for_trace(output_state),
            latency_ms=round(latency_ms, 3),
            token_usage=token_usage,
            timestamp=self._utc_now_iso(),
            status=status,
            error=error_text,
        )
        self.add_step(step)

    @staticmethod
    def _extract_state(args: Iterable[Any], kwargs: Mapping[str, Any]) -> Any:
        """Extracts a best-effort state payload from a node call."""
        args_list = list(args)
        if args_list:
            return args_list[0]
        if "state" in kwargs:
            return kwargs["state"]
        return {"args": args_list, "kwargs": dict(kwargs)}

    @staticmethod
    def _estimate_tokens(input_state: Any, output_state: Any) -> int:
        """Approximates token usage from serialized input and output payloads."""
        input_text = AgentTracer._safe_json_text(input_state)
        output_text = AgentTracer._safe_json_text(output_state)
        combined = f"{input_text} {output_text}".strip()
        if not combined:
            return 0
        return max(1, len(combined.split()))

    @staticmethod
    def _clone_for_trace(value: Any) -> Any:
        """Creates a JSON-safe snapshot for stable trace serialization."""
        try:
            return json.loads(json.dumps(value, default=AgentTracer._json_fallback))
        except Exception:
            return repr(value)

    @staticmethod
    def _safe_json_text(value: Any) -> str:
        """Converts any value into a compact JSON-like text representation."""
        try:
            return json.dumps(value, default=AgentTracer._json_fallback, separators=(",", ":"))
        except Exception:
            return repr(value)

    @staticmethod
    def _json_fallback(value: Any) -> Any:
        """Fallback serializer for non-JSON-native Python objects."""
        return repr(value)

    @staticmethod
    def _utc_now_iso() -> str:
        """Returns an ISO-8601 timestamp in UTC."""
        return datetime.now(timezone.utc).isoformat()
