# Generated by GitHub Copilot
"""FastAPI endpoints for storing and retrieving agent traces."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, List, Literal, Optional
from uuid import uuid4

from fastapi import FastAPI, Request, Response
from pydantic import BaseModel, Field

from src.tracer import AgentTracer, TraceStep

app = FastAPI(title="agent-tracer", version="0.1.0")
tracer = AgentTracer()


class TraceStepPayload(BaseModel):
    """Represents a trace step sent to the API for persistence."""

    node_name: str = Field(..., min_length=1, max_length=200)
    input_state: Any = None
    output_state: Any = None
    latency_ms: float = Field(..., ge=0.0)
    token_usage: int = Field(0, ge=0)
    timestamp: Optional[str] = None
    status: Literal["success", "error"] = "success"
    error: Optional[str] = None


class TraceIngestRequest(BaseModel):
    """Represents a trace ingestion request body."""

    steps: List[TraceStepPayload] = Field(default_factory=list, min_length=1)


@app.middleware("http")
async def add_request_metadata(request: Request, call_next: Any) -> Response:
    """Adds request-id and baseline security headers to each response."""
    request_id = request.headers.get("X-Request-ID") or str(uuid4())
    response = await call_next(request)
    response.headers["X-Request-ID"] = request_id
    response.headers["X-Frame-Options"] = "DENY"
    response.headers["X-Content-Type-Options"] = "nosniff"
    response.headers["Referrer-Policy"] = "no-referrer"
    return response


@app.get("/health")
def health() -> dict[str, Any]:
    """Returns a lightweight service health summary."""
    return {
        "status": "ok",
        "service": "agent-tracer",
        "trace_steps": len(tracer.get_steps()),
    }


@app.post("/trace")
def ingest_trace(payload: TraceIngestRequest) -> dict[str, Any]:
    """Stores one or more trace steps in memory."""
    for step in payload.steps:
        tracer.add_step(
            TraceStep(
                node_name=step.node_name,
                input_state=step.input_state,
                output_state=step.output_state,
                latency_ms=round(step.latency_ms, 3),
                token_usage=step.token_usage,
                timestamp=step.timestamp or datetime.now(timezone.utc).isoformat(),
                status=step.status,
                error=step.error,
            )
        )

    return {
        "stored": len(payload.steps),
        "total_steps": len(tracer.get_steps()),
    }


@app.get("/trace/latest")
def latest_trace(limit: int = 200) -> dict[str, Any]:
    """Returns the latest recorded trace steps with optional limiting."""
    steps = tracer.get_steps()
    safe_limit = max(1, min(limit, 2000))
    sliced = steps[-safe_limit:]
    return {
        "count": len(sliced),
        "steps": [step.to_dict() for step in sliced],
    }


@app.delete("/trace")
def clear_trace() -> dict[str, Any]:
    """Clears all in-memory trace data."""
    tracer.clear()
    return {"status": "cleared"}
