
"""FastAPI endpoints for storing and retrieving agent traces."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
import os
from threading import Lock
from time import monotonic
from typing import Annotated, Any, List, Literal, Optional
from uuid import uuid4

from fastapi import Depends, FastAPI, Header, HTTPException, Query, Request, Response
from pydantic import BaseModel, Field

from src.tracer import AgentTracer, TraceStep

app = FastAPI(title="agent-tracer", version="0.1.0")
tracer = AgentTracer()


# Generated by GitHub Copilot
@dataclass(frozen=True)
class Settings:
    """Runtime settings for API authentication and request throttling."""

    api_key: str
    rate_limit_per_minute: int


# Generated by GitHub Copilot
class InMemoryRateLimiter:
    """Simple per-client fixed-window rate limiter for write endpoints."""

    def __init__(self, window_seconds: int = 60) -> None:
        """Initialize a fixed-window limiter with in-memory request timestamps."""

        self.window_seconds = window_seconds
        self._events: dict[str, list[float]] = {}
        self._lock = Lock()

    def allow(self, key: str, limit: int) -> bool:
        """Return True when request is within rate limit for provided client key."""

        now = monotonic()
        window_start = now - self.window_seconds

        with self._lock:
            timeline = [timestamp for timestamp in self._events.get(key, []) if timestamp >= window_start]
            if len(timeline) >= limit:
                self._events[key] = timeline
                return False
            timeline.append(now)
            self._events[key] = timeline
        return True

    def clear(self) -> None:
        """Reset limiter state; intended for tests and controlled maintenance."""

        with self._lock:
            self._events.clear()


# Generated by GitHub Copilot
def _load_settings() -> Settings:
    """Load auth and rate-limit controls from environment variables."""

    return Settings(
        api_key=os.getenv("AGENT_TRACER_API_KEY", "").strip(),
        rate_limit_per_minute=int(os.getenv("AGENT_TRACER_RATE_LIMIT_PER_MINUTE", "600")),
    )


# Generated by GitHub Copilot
def _require_api_key(
    x_api_key: Annotated[str | None, Header(alias="X-API-Key")] = None,
) -> None:
    """Validate optional API key authentication for protected endpoints."""

    if not settings.api_key:
        return
    if x_api_key != settings.api_key:
        raise HTTPException(status_code=401, detail="Unauthorized")


# Generated by GitHub Copilot
def _enforce_write_rate_limit(request: Request) -> None:
    """Reject write requests that exceed per-client in-memory throttle settings."""

    client_key = request.client.host if request.client and request.client.host else "unknown"
    if not rate_limiter.allow(client_key, settings.rate_limit_per_minute):
        raise HTTPException(status_code=429, detail="Rate limit exceeded")


settings = _load_settings()
rate_limiter = InMemoryRateLimiter(window_seconds=60)
AuthDep = Annotated[None, Depends(_require_api_key)]


class TraceStepPayload(BaseModel):
    """Represents a trace step sent to the API for persistence."""

    node_name: str = Field(..., min_length=1, max_length=200)
    input_state: Any = None
    output_state: Any = None
    latency_ms: float = Field(..., ge=0.0)
    token_usage: int = Field(0, ge=0)
    timestamp: Optional[str] = None
    status: Literal["success", "error"] = "success"
    error: Optional[str] = None


class TraceIngestRequest(BaseModel):
    """Represents a trace ingestion request body."""

    steps: List[TraceStepPayload] = Field(default_factory=list, min_length=1)


@app.middleware("http")
async def add_request_metadata(request: Request, call_next: Any) -> Response:
    """Adds request-id and baseline security headers to each response."""
    request_id = request.headers.get("X-Request-ID") or str(uuid4())
    response = await call_next(request)
    response.headers["X-Request-ID"] = request_id
    response.headers["X-Frame-Options"] = "DENY"
    response.headers["X-Content-Type-Options"] = "nosniff"
    response.headers["Referrer-Policy"] = "strict-origin-when-cross-origin"
    response.headers["Permissions-Policy"] = "camera=(), microphone=(), geolocation=()"
    return response


@app.get("/health")
def health() -> dict[str, Any]:
    """Returns a lightweight service health summary."""
    return {
        "status": "ok",
        "service": "agent-tracer",
        "trace_steps": len(tracer.get_steps()),
    }


@app.post("/trace")
def ingest_trace(payload: TraceIngestRequest, request: Request, _: AuthDep = None) -> dict[str, Any]:
    """Stores one or more trace steps in memory."""

    _enforce_write_rate_limit(request)

    for step in payload.steps:
        tracer.add_step(
            TraceStep(
                node_name=step.node_name,
                input_state=step.input_state,
                output_state=step.output_state,
                latency_ms=round(step.latency_ms, 3),
                token_usage=step.token_usage,
                timestamp=step.timestamp or datetime.now(timezone.utc).isoformat(),
                status=step.status,
                error=step.error,
            )
        )

    return {
        "stored": len(payload.steps),
        "total_steps": len(tracer.get_steps()),
    }


@app.get("/trace/latest")
def latest_trace(
    limit: int = Query(default=200, ge=1, le=2000),
    _: AuthDep = None,
) -> dict[str, Any]:
    """Returns the latest recorded trace steps with optional limiting."""

    steps = tracer.get_steps()
    sliced = steps[-limit:]
    return {
        "count": len(sliced),
        "steps": [step.to_dict() for step in sliced],
    }


@app.delete("/trace")
def clear_trace(request: Request, _: AuthDep = None) -> dict[str, Any]:
    """Clears all in-memory trace data."""

    _enforce_write_rate_limit(request)

    tracer.clear()
    return {"status": "cleared"}
