"""FastAPI endpoints for storing and retrieving agent traces."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
import logging
import os
from threading import Lock
from time import monotonic
from typing import Annotated, Any, List, Literal, Optional
from uuid import uuid4

from fastapi import Depends, FastAPI, Header, HTTPException, Query, Request, Response
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.gzip import GZipMiddleware
from fastapi.middleware.trustedhost import TrustedHostMiddleware
from pydantic import BaseModel, Field

from src.tracer import AgentTracer, TraceStep

DEFAULT_ALLOWED_ORIGINS = "http://127.0.0.1:4178,http://localhost:4178"
DEFAULT_ALLOWED_HOSTS = "*"


# Generated by GitHub Copilot
@dataclass(frozen=True)
class Settings:
    """Runtime settings for API authentication, networking controls, and retention."""

    api_key: str
    rate_limit_per_minute: int
    max_trace_steps: int
    allowed_origins: tuple[str, ...]
    allowed_hosts: tuple[str, ...]
    enable_docs: bool
    enable_gzip: bool
    hsts_seconds: int
    log_level: str


# Generated by GitHub Copilot
class InMemoryRateLimiter:
    """Simple per-client fixed-window rate limiter for write endpoints."""

    def __init__(self, window_seconds: int = 60) -> None:
        """Initialize a fixed-window limiter with in-memory request timestamps."""

        self.window_seconds = window_seconds
        self._events: dict[str, list[float]] = {}
        self._lock = Lock()

    def allow(self, key: str, limit: int) -> bool:
        """Return True when request is within rate limit for provided client key."""

        now = monotonic()
        window_start = now - self.window_seconds

        with self._lock:
            timeline = [timestamp for timestamp in self._events.get(key, []) if timestamp >= window_start]
            if len(timeline) >= limit:
                self._events[key] = timeline
                return False
            timeline.append(now)
            self._events[key] = timeline
        return True

    def clear(self) -> None:
        """Reset limiter state; intended for tests and controlled maintenance."""

        with self._lock:
            self._events.clear()


# Generated by GitHub Copilot
def _split_csv(value: str) -> tuple[str, ...]:
    """Split comma-separated env values into a deduplicated tuple."""

    parts = [part.strip() for part in value.split(",") if part.strip()]
    if not parts:
        return tuple()
    return tuple(dict.fromkeys(parts))


# Generated by GitHub Copilot
def _parse_bool_env(name: str, default: bool) -> bool:
    """Parse a boolean environment variable with strict accepted values."""

    raw = os.getenv(name)
    if raw is None or not raw.strip():
        return default

    normalized = raw.strip().lower()
    if normalized in {"1", "true", "yes", "on"}:
        return True
    if normalized in {"0", "false", "no", "off"}:
        return False
    raise RuntimeError(f"Invalid boolean value for {name}: {raw}")


# Generated by GitHub Copilot
def _parse_int_env(name: str, default: int, min_value: int, max_value: int) -> int:
    """Parse and range-check integer environment variables."""

    raw = os.getenv(name)
    if raw is None or not raw.strip():
        return default

    try:
        value = int(raw.strip())
    except ValueError as exc:
        raise RuntimeError(f"Invalid integer value for {name}: {raw}") from exc

    if value < min_value or value > max_value:
        raise RuntimeError(
            f"{name} must be between {min_value} and {max_value}; received {value}"
        )
    return value


# Generated by GitHub Copilot
def _load_settings() -> Settings:
    """Load auth, retention, and networking controls from environment variables."""

    return Settings(
        api_key=os.getenv("AGENT_TRACER_API_KEY", "").strip(),
        rate_limit_per_minute=_parse_int_env(
            "AGENT_TRACER_RATE_LIMIT_PER_MINUTE",
            default=600,
            min_value=1,
            max_value=100_000,
        ),
        max_trace_steps=_parse_int_env(
            "AGENT_TRACER_MAX_STEPS",
            default=10_000,
            min_value=1,
            max_value=1_000_000,
        ),
        allowed_origins=_split_csv(os.getenv("AGENT_TRACER_ALLOWED_ORIGINS", DEFAULT_ALLOWED_ORIGINS)),
        allowed_hosts=_split_csv(os.getenv("AGENT_TRACER_ALLOWED_HOSTS", DEFAULT_ALLOWED_HOSTS)),
        enable_docs=_parse_bool_env("AGENT_TRACER_ENABLE_DOCS", default=True),
        enable_gzip=_parse_bool_env("AGENT_TRACER_ENABLE_GZIP", default=True),
        hsts_seconds=_parse_int_env(
            "AGENT_TRACER_HSTS_SECONDS",
            default=0,
            min_value=0,
            max_value=31_536_000,
        ),
        log_level=os.getenv("AGENT_TRACER_LOG_LEVEL", "INFO").strip().upper() or "INFO",
    )


# Generated by GitHub Copilot
def _configure_logging(runtime_settings: Settings) -> None:
    """Configure module logging from runtime settings."""

    level_name = runtime_settings.log_level if runtime_settings.log_level else "INFO"
    level = getattr(logging, level_name, logging.INFO)
    logging.basicConfig(
        level=level,
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
    )


# Generated by GitHub Copilot
def _require_api_key(
    x_api_key: Annotated[str | None, Header(alias="X-API-Key")] = None,
) -> None:
    """Validate optional API key authentication for protected endpoints."""

    if not settings.api_key:
        return
    if x_api_key != settings.api_key:
        raise HTTPException(status_code=401, detail="Unauthorized")


# Generated by GitHub Copilot
def _enforce_write_rate_limit(request: Request) -> None:
    """Reject write requests that exceed per-client in-memory throttle settings."""

    client_key = request.client.host if request.client and request.client.host else "unknown"
    if not rate_limiter.allow(client_key, settings.rate_limit_per_minute):
        raise HTTPException(status_code=429, detail="Rate limit exceeded")


settings = _load_settings()
_configure_logging(settings)
logger = logging.getLogger("agent_tracer.api")

app = FastAPI(
    title="agent-tracer",
    version="0.1.0",
    docs_url="/docs" if settings.enable_docs else None,
    redoc_url="/redoc" if settings.enable_docs else None,
    openapi_url="/openapi.json" if settings.enable_docs else None,
)

if settings.enable_gzip:
    app.add_middleware(GZipMiddleware, minimum_size=500)

app.add_middleware(
    TrustedHostMiddleware,
    allowed_hosts=list(settings.allowed_hosts) if settings.allowed_hosts else ["*"],
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=list(settings.allowed_origins) if settings.allowed_origins else ["*"],
    allow_methods=["GET", "POST", "DELETE", "OPTIONS"],
    allow_headers=["Authorization", "Content-Type", "X-API-Key", "X-Request-ID"],
    expose_headers=["X-Request-ID"],
    allow_credentials=False,
    max_age=3600,
)

tracer = AgentTracer(max_steps=settings.max_trace_steps)
rate_limiter = InMemoryRateLimiter(window_seconds=60)
AuthDep = Annotated[None, Depends(_require_api_key)]
APP_STARTED_AT = monotonic()


class TraceStepPayload(BaseModel):
    """Represents a trace step sent to the API for persistence."""

    node_name: str = Field(..., min_length=1, max_length=200)
    input_state: Any = None
    output_state: Any = None
    latency_ms: float = Field(..., ge=0.0)
    token_usage: int = Field(0, ge=0)
    timestamp: Optional[str] = None
    status: Literal["success", "error"] = "success"
    error: Optional[str] = None


class TraceIngestRequest(BaseModel):
    """Represents a trace ingestion request body."""

    steps: List[TraceStepPayload] = Field(default_factory=list, min_length=1)


# Generated by GitHub Copilot
@app.middleware("http")
async def add_request_metadata(request: Request, call_next: Any) -> Response:
    """Attach request identifiers, security headers, and request logs."""

    request_id = request.headers.get("X-Request-ID") or str(uuid4())
    started = monotonic()

    try:
        response = await call_next(request)
    except Exception:
        elapsed_ms = (monotonic() - started) * 1000.0
        logger.exception(
            "Unhandled request failure method=%s path=%s duration_ms=%.2f request_id=%s",
            request.method,
            request.url.path,
            elapsed_ms,
            request_id,
        )
        raise

    elapsed_ms = (monotonic() - started) * 1000.0

    response.headers["X-Request-ID"] = request_id
    response.headers["X-Frame-Options"] = "DENY"
    response.headers["X-Content-Type-Options"] = "nosniff"
    response.headers["Referrer-Policy"] = "no-referrer"
    response.headers["Permissions-Policy"] = "camera=(), microphone=(), geolocation=()"
    response.headers["Content-Security-Policy"] = (
        "default-src 'none'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'"
    )
    response.headers["Cache-Control"] = "no-store"
    response.headers["Pragma"] = "no-cache"

    if settings.hsts_seconds > 0:
        response.headers["Strict-Transport-Security"] = f"max-age={settings.hsts_seconds}; includeSubDomains"

    logger.info(
        "Request completed method=%s path=%s status=%s duration_ms=%.2f request_id=%s",
        request.method,
        request.url.path,
        response.status_code,
        elapsed_ms,
        request_id,
    )
    return response


@app.get("/health")
def health() -> dict[str, Any]:
    """Return a lightweight service health summary for uptime probes."""

    return {
        "status": "ok",
        "service": "agent-tracer",
        "trace_steps": len(tracer.get_steps()),
        "uptime_seconds": round(monotonic() - APP_STARTED_AT, 3),
    }


@app.get("/ready")
def ready() -> dict[str, Any]:
    """Return readiness state for deployment orchestrators."""

    return {
        "status": "ready",
        "service": "agent-tracer",
        "max_trace_steps": tracer.get_max_steps(),
        "rate_limit_per_minute": settings.rate_limit_per_minute,
    }


@app.post("/trace")
def ingest_trace(payload: TraceIngestRequest, request: Request, _: AuthDep = None) -> dict[str, Any]:
    """Store one or more trace steps in bounded in-memory retention."""

    _enforce_write_rate_limit(request)

    for step in payload.steps:
        tracer.add_step(
            TraceStep(
                node_name=step.node_name,
                input_state=step.input_state,
                output_state=step.output_state,
                latency_ms=round(step.latency_ms, 3),
                token_usage=step.token_usage,
                timestamp=step.timestamp or datetime.now(timezone.utc).isoformat(),
                status=step.status,
                error=step.error,
            )
        )

    return {
        "stored": len(payload.steps),
        "total_steps": len(tracer.get_steps()),
        "max_trace_steps": tracer.get_max_steps(),
    }


@app.get("/trace/latest")
def latest_trace(
    limit: int = Query(default=200, ge=1, le=2000),
    _: AuthDep = None,
) -> dict[str, Any]:
    """Return latest recorded trace steps with retention-aware limiting."""

    steps = tracer.get_steps()
    max_limit = min(2000, tracer.get_max_steps())
    effective_limit = min(limit, max_limit)
    sliced = steps[-effective_limit:]
    return {
        "count": len(sliced),
        "steps": [step.to_dict() for step in sliced],
    }


@app.delete("/trace")
def clear_trace(request: Request, _: AuthDep = None) -> dict[str, Any]:
    """Clear all in-memory trace data."""

    _enforce_write_rate_limit(request)

    tracer.clear()
    return {"status": "cleared"}
